package juego.tablero;

public enum Direccion {

	ARRIBA,
	ABAJO,
	IZQUIERDA,
	DERECHA,
	ADELANTE,
	ATRAS,
	IZQUIERDA_ARRIBA,
	IZQUIERDA_ABAJO, 	
	DERECHA_ARRIBA,
	DERECHA_ABAJO,
	ADELANTE_ARRIBA,
	ADELANTE_ABAJO,
	ADELANTE_IZQUIERDA,
	ADELANTE_DERECHA,
	ADELANTE_DERECHA_ARRIBA,
	ADELANTE_DERECHA_ABAJO,
	ADELANTE_IZQUIERDA_ARRIBA,
	ADELANTE_IZQUIERDA_ABAJO,
	ATRAS_ARRIBA,
	ATRAS_ABAJO,
	ATRAS_IZQUIERDA,
	ATRAS_DERECHA,
	ATRAS_DERECHA_ARRIBA,
	ATRAS_DERECHA_ABAJO,
	ATRAS_IZQUIERDA_ARRIBA,
	ATRAS_IZQUIERDA_ABAJO,
	
}
